# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3edd3fd3d23546701871abc2a352f36cba5f6c8b9fda69a93cf9d028f97642ffb11cd414e603f6fc2e9cb16b76e03a801c854e4632fdef32ea229ef122823065

test:
  secret_key_base: 2d0602b7291595fcb54e7180e06971c1ec38034e35b2b02cdd0ef5a9d4cde209ebd3d13c0b8b1533ce3136e7a188debb1098b22f0398cc24c55cd0a4ae56f24b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
